### ISSUE TITLE
Version CAS

### ISSUE THREAD

**Issue by AmarKhoirudin** [subfission/cas#104]
hello brother, please help, how do I change the CAS version because I need CAS version 3??

![image](https://user-images.githubusercontent.com/42802825/141885582-c29013c6-cc55-4885-8197-a3de3741aec0.png)

![image](https://user-images.githubusercontent.com/42802825/141885494-790d54f9-6179-4806-8cda-f523f49ca5a1.png)

**Comment by subfission** [comment]
The easiest way is to set `CAS_VERSION` in your .env file to `3.0`.  Otherwise, this is set by the default value of 3.0.  I have no idea what **1.4.0** is referencing.
