### ISSUE TITLE
Feasibility of working in Laravel 9

### ISSUE THREAD

**Issue by MFranklinJ** [subfission/cas#105]
I'm trying to implement this feature in Laravel 9. But facing some unsupported issues. I want to know whether we can use this with Laravel 9 or not? If yes, do I need to do any changes? what is the version I have to use?

**Comment by nasrulhazim** [comment]
I've made a PR for Laravel 9 support - https://github.com/subfission/cas/pull/106

**Comment by subfission** [comment]
Added update in v4.2.0
