### ISSUE TITLE
Issue while implementing cas in Laravel 9

### ISSUE THREAD

**Issue by MFranklinJ** [subfission/cas#107]
I'm trying to implement this cas in Laravel 9. my code for installing cas is $ composer require "subfission/cas":"4.1.0" When trying with this command I'm getting the below error. 

Problem 1
    - Root composer.json requires subfission/cas 4.1.0 -> satisfiable by subfission/cas[v4.1.0].
    - subfission/cas v4.1.0 requires illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Please let me know whether my command is correct or not. If not please guide me with right one. If right then guide me to sort this issue out.

**Comment by MFranklinJ** [comment]
Can I get the response for my above clarification ASAP?

**Comment by ikram749** [comment]
any update for these issues?

**Comment by MFranklinJ** [comment]
Since I dont get any response from the author, I started using Laravel 8. Its working well with Laravel 8.

**Comment by nasrulhazim** [comment]
@MFranklinJ , can use from my repo - #106

**Comment by timcortesi** [comment]
@nasrulhazim can you add your repo to packagist so we can use with composer?  
https://packagist.org/packages/subfission/cas

**Comment by desyashasyi** [comment]
> @MFranklinJ , can use from my repo - #106

How to use your repo in establish Subfission CAS?

**Comment by nasrulhazim** [comment]
> > @MFranklinJ , can use from my repo - #106
> 
> How to use your repo in establish Subfission CAS?

Add the following in your `composer.json`:

```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/nasrulhazim/cas"
    }
]
```

and update the package version to:

```json
"subfission/cas": "dev-master",
```

Then run `composer update`.

Click [here](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) for reference.

**Comment by subfission** [comment]
Laravel 9 requires illuminate/support v9.  You just needed to add v9 to composer.  Laravel 8 uses v8 which is why that worked.
