### ISSUE TITLE
Authentication is not cleaned from session on logout

### ISSUE THREAD

**Issue by progmars** [subfission/cas#11]
The code in Sso.php which is shown below is not working as expected:

```
if ($this->auth->check()) {
            $this->auth->logout();
        }
Session::flush();
phpCAS::logout();
exit;
```

Session::flush() does not actually save the session, but only cleans out the variable from memory. Session file is actually saved in Laravel's application shutdown handlers, therefore even auth->logout does not work and keep the id stored in the session if you call `exit` prematurely.

You should not call `exit` to allow Laravel's shutdown handlers to do their job.

Alternatively, `Session::save()` also seems to work.

**Comment by subfission** [comment]
Resolved this issue with this commit:
(https://github.com/subfission/cas/commit/25519bcfc86ebe1d25c37c4242774134ecfcc565)
