### ISSUE TITLE
Undefined array key "cas_client_service"

### ISSUE THREAD

**Issue by legendscraft** [subfission/cas#121]
The array key _cas_client_service_ has not been defined in **parseConfig** 

https://github.com/subfission/cas/blob/ca3150f42ccf84d1e2c232ce84327f799697a0e9/src/Subfission/Cas/CasManager.php#L121

Below is the error I am getting as a result of this

![2023-03-29_10-19](https://user-images.githubusercontent.com/61534760/228456589-35aee7d5-60fc-4484-b653-b830eac9fb37.png)

**Comment by subfission** [comment]
This identified some missing proper error handling.

But you are missing your config values for the service, which caused the error: https://github.com/subfission/cas/blob/9fed4eb7496c5caec45c3f6a9112a211eded39e7/src/config/config.php#L68

**Comment by desyashasyi** [comment]
Hi, I have the same problem. I use the config file of the previous version of Laravel 9. But when I enable the  'cas_client_service' => env('CAS_CLIENT_SERVICE', 'http://localhost'), 

I got this error

![image](https://github.com/subfission/cas/assets/48233515/e165115c-ef49-4981-8a35-e480da0948a9)


I changed to 'cas_client_service' => env('CAS_CLIENT_SERVICE', '127.0.0.1:8000'),

The problem is similar

**Comment by desyashasyi** [comment]
So which setting should be used?

**Comment by desyashasyi** [comment]
https://github.com/subfission/cas/assets/48233515/ad52ab58-dcaf-43e2-9d9e-3049cf25c313

**Comment by SvenMandic** [comment]
> Hi, I have the same problem. I use the config file of the previous version of Laravel 9. But when I enable the 'cas_client_service' => env('CAS_CLIENT_SERVICE', 'http://localhost'),
> 
> I got this error
> 
> ![image](https://user-images.githubusercontent.com/48233515/243165971-e165115c-ef49-4981-8a35-e480da0948a9.png)
> 
> I changed to 'cas_client_service' => env('CAS_CLIENT_SERVICE', '127.0.0.1:8000'),
> 
> The problem is similar

I have same error. Did you manage to fix this?

**Comment by Glifaus** [comment]
Hi! I have got the same error earlier today.

I fixed it by updating cas.php file in config comparing with original: [cas/src/config/config.php](https://github.com/subfission/cas/blob/9fed4eb7496c5caec45c3f6a9112a211eded39e7/src/config/config.php#L68)
And adding to the .env file this new parameter:
CAS_CLIENT_SERVICE="http://xxxxxxx.test/"
When this url is the local environment url to my project. Check carefully Cas.php config to change the url's needed.

**Comment by desyashasyi** [comment]
> > Hi, I have the same problem. I use the config file of the previous version of Laravel 9. But when I enable the 'cas_client_service' => env('CAS_CLIENT_SERVICE', 'http://localhost'),
> > I got this error
> > ![image](https://user-images.githubusercontent.com/48233515/243165971-e165115c-ef49-4981-8a35-e480da0948a9.png)
> > I changed to 'cas_client_service' => env('CAS_CLIENT_SERVICE', '127.0.0.1:8000'),
> > The problem is similar
> 
> I have same error. Did you manage to fix this?



> > Hi, I have the same problem. I use the config file of the previous version of Laravel 9. But when I enable the 'cas_client_service' => env('CAS_CLIENT_SERVICE', 'http://localhost'),
> > I got this error
> > ![image](https://user-images.githubusercontent.com/48233515/243165971-e165115c-ef49-4981-8a35-e480da0948a9.png)
> > I changed to 'cas_client_service' => env('CAS_CLIENT_SERVICE', '127.0.0.1:8000'),
> > The problem is similar
> 
> I have same error. Did you manage to fix this?

I still have such error

**Comment by desyashasyi** [comment]
> Hi! I have got the same error earlier today.
> 
> I fixed it by updating cas.php file in config comparing with original: [cas/src/config/config.php](https://github.com/subfission/cas/blob/9fed4eb7496c5caec45c3f6a9112a211eded39e7/src/config/config.php#L68) And adding to the .env file this new parameter: CAS_CLIENT_SERVICE="http://xxxxxxx.test/" When this url is the local environment url to my project. Check carefully Cas.php config to change the url's needed.

I tried your solution, but there is another error

![image](https://github.com/subfission/cas/assets/48233515/ba2f5267-f415-45c1-bf71-48cdc79a1774)

**Comment by desyashasyi** [comment]
is there any update?

**Comment by subfission** [comment]
Hi folks, this is not a bug in this codebase.  This error is because you are sending a SAML request to a nonexistent resource or an endpoint that does not support the SAML/CAS protocols.  Please check your SAML targets and match your config to them.  These should be your SAML providers.

For reference see:
https://github.com/subfission/cas/blob/9fed4eb7496c5caec45c3f6a9112a211eded39e7/src/Subfission/Cas/CasManager.php#L121C3-L121C3

Check phpCAS for more detail on how this is used correctly.
