### ISSUE TITLE
Conflict with Pest : Only first feature test to run

### ISSUE THREAD

**Issue by then8885** [subfission/cas#137]
Hi, thank you for this library 👍 

With laravel 11.x and Pest, as soon as the facade is created, Pest cannot list and run all feature tests anymore.

**Steps to reproduce :** 

1. start a fresh project using laravel installer ´laravel new testname´; no starter kit, pest.
2. add a second feature test 
3. `php artisan test` 
4. Validate that 2 feature tests have been tested.
5. `composer require subfission/cas`
6. Add the facade initialisation in `AppServiceProvider.php`
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void { }

    public function boot(): void
    {
        app('cas');
    }
}
```
7. `php artisan test`
8. **Notice** that now only the first alphabetically feature test have been tested.

So far, I've nailed down the issue to [$this->configureCas($this->config['cas_proxy'] ? 'proxy' : 'client');](https://github.com/subfission/cas/blob/v5.1.0/src/Subfission/Cas/CasManager.php#L79) 
By commenting this line, Pest succeed again to list and run all tests. But obviously CasManager is not happy.

I'm going to dive a bit deeper, but I will have to learn a bit more about this library and cas in general.

**Comment by dstepe** [comment]
Before you dig much further, you should take a look at issue #125. Your symptoms are very similar and I suspect have the same underlying cause. This gets into some fundamental test considerations that need to be addressed for an external dependency within your app. You should avoid them at all costs when running tests.

**Comment by then8885** [comment]
Thanks for the feedback.
I was indeed on that track.

`CAS_GracefullTerminationException::throwInsteadOfExiting();` helped a lot, as I was finally able to have a clue of what happend.

I should have failed somewhere, as tests should already have been using a mock implementation of CasManager.
