### ISSUE TITLE
Update jasig/phpcas to 1.3.4

### ISSUE THREAD

**Issue by CaporalDead** [subfission/cas#15]
Hi,

Can you update your dependency to jasig/phpcas 1.3.4 instead of 1.3.3 because of a typo in jasig/phpcas 1.3.3 : https://github.com/Jasig/phpCAS/blob/1.3.3/source/CAS/Client.php#L892 fixed in 1.3.4 ?

Thanks. Great work btw :).

**Comment by subfission** [comment]
@CaporalDead I have been working on a new release for PHP7 support and the new version of CAS 1.3.4.   I just finished merging the new update after doing some testing with it the past few weeks.  Previously, this was under another branch, however now you will also find it under the tag v2.0.0.  I think this version is what you need.
