### ISSUE TITLE
BindingResolutionException

### ISSUE THREAD

**Issue by bandgeekndb** [subfission/cas#22]
Just installed your CAS package and I'm having issues getting some test code to work.  I wrote 2 simple routes to test the CAS authentication as follows:

```
Route::group(['middleware' => ['web']], function () {
    Route::get('/testcas', function(){
        Cas::authenticate();
        redirect('/home');
    });
});

Route::group(['middleware' => ['web', 'cas.auth']], function() {
    Route::get('/home', 'HomeController@index'); 
});
```

When trying to access the `/testcas` route, I get an exception:

> Illuminate \ Contracts \ Container \ BindingResolutionException
> 
> Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class Subfission\Cas\CasManager

I verified that the config file is successfully created and I set a number of values in it.  For now, I'm trying to use masquerade until I'm sure I have it working locally, then I'll connect to the CAS server.

Happy to provide more information and/or testing as needed, just let me know.  Thanks!

**Comment by sansanbgl** [comment]
Ill just rollback to 2.0.1

**Comment by subfission** [comment]
Great catch!  Master now updated to -> b40fab668f60d6d311b0758c00960a4239810e82 which solves this problem.

**Comment by nicozimmermann94** [comment]
I did a fresh install and I am getting the exact same error now.
EDIT: nevermind, I did not require the dev-master
