### ISSUE TITLE
CAS not redirecting back to Laravel application

### ISSUE THREAD

**Issue by bandgeekndb** [subfission/cas#23]
I'm not sure if this is an error in my application, or an error in the package, so forgive me if it is an app error!

I'm still testing the package, and I'm not being redirected back to my app after doing CAS authentication.

```
Route::group(['middleware' => ['web']], function () {
    Route::get('/login', function(){
        Cas::authenticate();
    });
});

Route::group(['middleware' => ['web', 'cas.auth']], function() {
    Route::get('/home', 'HomeController@index'); 
});
```

I turned on cas_debug and cas_verbose_errors and I have the resulting log file:

```
2929 .START (2016-04-18 17:09:41) phpCAS-1.3.4 ****************** [CAS.php:469]
2929 .=> phpCAS::client('S1', '<casurl>', 443, '', false) [CasManager.php:43]
2929 .|    => CAS_Client::__construct('S1', false, '<casurl>', 443, '', false) [CAS.php:361]
2929 .|    |    Starting a new session tve2sipa3jfjlgu8ll50k1vo57 [Client.php:906]
2929 .|    <= ''
2929 .<= ''
2929 .=> CAS_Client::handleLogoutRequests(true, array (  0 => '<casurl>',)) [CAS.php:1258]
2929 .|    Not a logout request [Client.php:1701]
2929 .<= ''
2929 .=> phpCAS::setNoCasServerValidation() [CasManager.php:94]
2929 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
2929 .<= ''
2929 .=> phpCAS::setServerLoginURL('<casLoginURL>') [CasManager.php:31]
2929 .<= ''
2929 .=> phpCAS::setServerLogoutURL('<casLogoutURL>') [CasManager.php:32]
2929 .<= ''
2929 .=> phpCAS::isAuthenticated() [CasManager.php:147]
2929 .|    => CAS_Client::isAuthenticated() [CAS.php:1127]
2929 .|    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
2929 .|    |    |    no user found [Client.php:1604]
2929 .|    |    <= false
2929 .|    |    no ticket found [Client.php:1463]
2929 .|    <= false
2929 .<= false
2929 .=> phpCAS::forceAuthentication() [CasManager.php:105]
2929 .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
2929 .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
2929 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
2929 .|    |    |    |    no user found [Client.php:1604]
2929 .|    |    |    <= false
2929 .|    |    |    no ticket found [Client.php:1463]
2929 .|    |    <= false
2929 .|    |    => CAS_Client::redirectToCas(false) [Client.php:1258]
2929 .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1625]
2929 .|    |    |    <= '<casLoginURL>'
2929 .|    |    |    Redirect to : <casLoginURL> [Client.php:1632]
2929 .|    |    |    exit()
2929 .|    |    |    -
2929 .|    |    -
2929 .|    -
```

Is there anything I'm missing?  I followed the instructions in the Readme and it looks like the CAS integration is mostly working, I just can't tell if the redirect issue is with my code or the package.  Thanks for your assistance!

**Comment by subfission** [comment]
Hi!  It looks like you have not added anything to your cas.php
configuration file.  Make sure you ran the vendor publish command for cas
to have the configuration file moved into place before editing.  Let me
know if you still have any issues.

**Comment by bandgeekndb** [comment]
Sorry, should have been a bit clearer, I am using .env directives to set the URLs, I just redacted them here in the snippets.  Wherever I put <casurl> or <casLoginURL> above, it correctly pulled the values from my .env file.  I've put a sanitized version of my .env directives below:

```
cas_hostname = test-cas.domain.com
cas_real_hosts = test-cas.domain.com
cas_login_url = https://test-cas.domain.com/login
cas_logout_url = https://test-cas.domain.com/logout
cas_debug = D:/wwwlogs/apps-test/cas.log
cas_verbose_errors = true
```

I also included the cas.php config file, just sanitized the domains.

```
'cas_hostname'        => env('CAS_HOSTNAME', 'cas.domain.com'),
'cas_real_hosts'      => env('CAS_REAL_HOSTS', 'cas.domain.com'),
'cas_session_name'    => env('CAS_SESSION_NAME', 'CASauth'),
'cas_control_session' => env('CAS_CONTROL_SESSIONS', false),
'cas_proxy'           => env('CAS_PROXY', false),
'cas_port'            => env('CAS_PORT', 443),
'cas_uri'             => env('CAS_URI', ''),
'validation'          => env('CAS_VALIDATION', ''),
'cert'                => env('CAS_CERT', ''),
'cas_validate_cn'     => env('CAS_VALIDATE_CN', true),
'cas_login_url'       => env('CAS_LOGIN_URL', 'https://cas.domain.com/login'),
'cas_logout_url'      => env('CAS_LOGOUT_URL', 'https://cas.domain.com/logout'),
'cas_redirect_path'   => env('CAS_REDIRECT_PATH', '/home'),
'cas_enable_saml'     => env('CAS_ENABLE_SAML', true),
'cas_debug'           => env('CAS_DEBUG', false),
'cas_verbose_errors'  => env('CAS_VERBOSE_ERRORS', false),
'cas_masquerade'      => env('CAS_MASQUERADE', '')
```

I'm working in my test region, which is why the .env file is pointing the app to test-cas.  The default, if there's ever an error reading the .env, should be the production cas instance, so that's why it's the default in the config file.

Sorry for the confusion, should have made it clearer that I had sanitized the logs a bit.

**Comment by subfission** [comment]
I believe your env file entries are case sensitive.

**Comment by subfission** [comment]
Okay, after looking further into this, your config is a bit different than mine.  First of all, does your CAS auth service redirect?  I use this:

```
'cas_redirect_path'   => env('CAS_REDIRECT_PATH', 'home'),
```

Also, does your server not have a cas url?

```
'cas_uri'                    => env('CAS_URI', ''),
```

Usually this is:

```
'cas_uri'                    => env('CAS_URI', '/cas'),
```

I'm running the dev-master version of this right now and it is working fully.  If you can try these fixes and report back to me, it should give us more insight into your issue.

The concerning line to me from your log is this:

```
Redirect to : <casLoginURL> [Client.php:1632]
```

Can you check the url and verify this url is accurate?

**Comment by bandgeekndb** [comment]
I tried both /home and home as the redirect path, neither worked.  I know the service redirects, other applications setup to use the CAS service redirect without issue.

Our CAS server does not have a trailing path, we just use cas.domain.com/login and cas.domain.com/logout as our URLs.  I tried with both our test and prod CAS instances, both exhibit the same behavior, I'm able to login without issue, but no redirecting back to the app and going to the app's URL manually acts as if I'm not logged in, even though CAS acknowledges I am authenticated.

**Comment by subfission** [comment]
This is absolutely puzzling... Can you verify a 302 redirect from your CAS auth website?  What happens at the networking level after you complete the sign on?

**Comment by bandgeekndb** [comment]
Wireshark gets us closer!

I have a Confluence site that uses CAS, that redirects just fine, so I used it for testing here.

Working CAS conversation starts with a GET request to /login with a service GET variable:

`GET /login?service=https%3A%2F%2Fstaff.domain.com%2Fpages%2Fviewpage.action%3FspaceKey%3Dintranet%26title%3DHome&os_destination=%2F HTTP/1.1`

When I try to use CAS on my Laravel site, I get a plain GET request without the service variable:

`GET /login HTTP/1.1`

Without that service GET variable, CAS doesn't know how to redirect back to our application.  Am I missing a config setting that will let that be passed?

**Comment by subfission** [comment]
Sorry for the delayed response.

I believe this can all be fixed by changing your config from:

  'cas_login_url'       => env('CAS_LOGIN_URL', 'https://cas.domain.com/login'),

to 

  'cas_login_url'       => env('CAS_LOGIN_URL', 'https://cas.domain.com/login?service=$URL'),

where $URL is your url encoded redirect.

I am currently prototyping a new version that will enable method passthru to phpCAS and provide some additional SAML enhancements... In the meantime, that should solve your issue.

Let me know if that works and I'll close this issue.

**Comment by subfission** [comment]
Okay, try the new update on the master branch.  You will see some enhancements added.

```
$ composer require "subfission/cas":"dev-master"
```

For your setup:

```
'cas_login_url'       => env('CAS_LOGIN_URL', 'https://cas.domain.com/login'),
'cas_redirect_path'   => env('CAS_REDIRECT_PATH', 'https://path-to-your-app-homepage.app'),
```

This should solve the url issue.  Let me know if that works for you.
