### ISSUE TITLE
Cas::logout not working

### ISSUE THREAD

**Issue by jesusvpct** [subfission/cas#25]
When calling Cas::logout from my route, the function is not logging out. In fact, using PHP Debug, I can see that the condition phpCAS::isSessionAuthenticated() avoid executing the phpCAS::logout()

**Comment by subfission** [comment]
Can you provide output from your CAS debug log and your?  I have the current master branch release working for me in a few different production environments so it may be specific to your environment.

**Comment by jesusvpct** [comment]
This is my configuration on .env
`CAS_DEBUG=true
CAS_HOSTNAME=autentica-des.upct.es
CAS_REAL_HOSTS=autentica-des.upct.es
CAS_PORT=443
CAS_URI=/cas
CAS_LOGOUT_URL=https://autentica-des.upct.es/cas/logout
CAS_SAML=false`

And this is phpCAS.log registered
`DE05 .START (2016-05-26 10:39:51) phpCAS-1.3.4 ****************** [CAS.php:469]
DE05 .Loaded configuration:
DE05 .autentica-des.upct.es
DE05 .autentica-des.upct.es
DE05 .CASAuth
DE05 .1
DE05 .
DE05 .443
DE05 ./cas
DE05 .
DE05 .
DE05 .1
DE05 .
DE05 .https://autentica-des.upct.es/cas/logout
DE05 .test
DE05 .
DE05 .1
DE05 .1
DE05 .
DE05 .
DE05 .=> phpCAS::client('S1', 'autentica-des.upct.es', 443, '/cas', true) [CasManager.php:53]
DE05 .|    => CAS_Client::__construct('S1', false, 'autentica-des.upct.es', 443, '/cas', true) [CAS.php:361]
DE05 .|    |    Starting a new session ST-51-IBV9EFxH4HlfXn9efOCe-autentica-des1 [Client.php:906]
DE05 .|    <= ''
DE05 .<= ''
DE05 .=> CAS_Client::handleLogoutRequests(true, array (  0 => 'autentica-des.upct.es',)) [CAS.php:1258]
DE05 .|    Not a logout request [Client.php:1701]
DE05 .<= ''
DE05 .=> phpCAS::setNoCasServerValidation() [CasManager.php:109]
DE05 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
DE05 .<= ''
DE05 .=> phpCAS::setServerLoginURL('') [CasManager.php:34]
DE05 .<= ''
DE05 .=> phpCAS::setServerLogoutURL('https://autentica-des.upct.es/cas/logout') [CasManager.php:42]
DE05 .<= ''
`

**Comment by subfission** [comment]
A couple notes...
1. CAS_SAML is not a valid token, unless you changed the code. CAS_ENABLE_SAML is what you need. 
2. If you intend to disable SAML, you can remove CAS_REAL_HOSTS as this is a function of SAML.
3. You are using the standard CAS port, you can remove that from your .env file as it is implied.

Most importantly:
There is no logout request captured in this debug.  It does look like you authenticated successfully though.

Please submit the rest of the debug output so I can see where you are stuck.

**Comment by subfission** [comment]
Also, for debugging you can also use CAS_VERBOSE_ERRORS=true for even more details.

**Comment by jesusvpct** [comment]
This is the log when going to my logout route:

```
3940 .START (2016-05-26 11:34:34) phpCAS-1.3.4 ****************** [CAS.php:469]
3940 .Loaded configuration:
3940 .autentica-des.upct.es
3940 .cas.myuniv.edu
3940 .CASAuth
3940 .
3940 .
3940 .443
3940 ./cas
3940 .
3940 .
3940 .1
3940 .
3940 .https://autentica-des.upct.es/cas/logout
3940 .test
3940 .
3940 .
3940 .1
3940 .1
3940 .
3940 .=> phpCAS::client('2.0', 'autentica-des.upct.es', 443, '/cas', false) [CasManager.php:53]
3940 .|    => CAS_Client::__construct('2.0', false, 'autentica-des.upct.es', 443, '/cas', false) [CAS.php:361]
3940 .|    |    Starting a new session ST-51-IBV9EFxH4HlfXn9efOCe-autentica-des1 [Client.php:906]
3940 .|    <= ''
3940 .<= ''
3940 .=> phpCAS::setNoCasServerValidation() [CasManager.php:109]
3940 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
3940 .<= ''
3940 .=> phpCAS::setServerLoginURL('') [CasManager.php:34]
3940 .<= ''
3940 .=> phpCAS::setServerLogoutURL('https://autentica-des.upct.es/cas/logout') [CasManager.php:42]
3940 .<= ''
```

It not show nothing about logout. I have this on my logout route:

```
Route::get('auth/logout', function()
{
    Cas::logout();
});
```

When debugging with PHP Debug, I can see that the condition phpCAS::isSessionAuthenticated() is false, so it never go into the phpCAS::logout():

```
public function logout()
    {
        if (phpCAS::isSessionAuthenticated())
        {
            if ($this->config['cas_logout_redirect'])
            {
                phpCAS::logoutWithRedirectService($this->config['cas_logout_redirect']);
            } else
            {
                phpCAS::logout();
            }
        }
    }
```

**Comment by subfission** [comment]
It looks like you are having an issue with your session storage.  Please add this code to your Route and submit the result of the logout on your browser.  Filter out any sensitive details with example characters if needed.

```
Route::get('auth/logout', function()
{
    echo '<pre> User Session:';
    var_dump( $_SESSION['phpCAS'] ); echo PHP_EOL;
    echo  Cas::isAuthenticated() ? "Authenticated User" : "Un-Authenticated User"; echo PHP_EOL;
    echo '</pre>';
    dd( Cas::user() );

    // Cas::logout();
});

```

**Comment by subfission** [comment]
Go ahead and run `composer update` for your project.  Commit https://github.com/subfission/cas/commit/a387b3a4b921322d1b66d647bf2ca885f1b0c5f3 should fix your issue and not break anything for anyone.  

I believe your issue to be session related.  During logout though, it is not imperative to check the existence of the session data, so we can safely forward the user.

I typically do this as the TGS may be confused by a logout request it wasn't anticipating (anomalous logout request):

```
if( cas()->isAuthenticated() ) {
    cas()->logout();
} else {
     redirect('/');
}
```

For now, you will see a line in your log file that shows a logout request was made using invalid session data, but will still hand the user off to the logout service.

**Comment by jesusvpct** [comment]
It seems that it works now.

Thanks!!!!!!
