### ISSUE TITLE
No support for logout with URL

### ISSUE THREAD

**Issue by forby** [subfission/cas#26]
You did a great job simplifying and updating the library from XavRsl, but now the logout function only checks for a service url instead of allowing parameters.  Any plan to include full array parameters or at least logoutWithUrl() support? Our system makes use of this option.  I don't mind submitting a PR to help out if the addition works with your plan.

**Comment by subfission** [comment]
Thanks @forby for the support.  Your request is completely valid.  I had initially stripped this out because of the depreciation of support from CAS servers.  I have re-implemented it back now for those that still need it in 8c81661.

```
logoutWithUrl($url)
```
