### ISSUE TITLE
Handle logout Requests from the CASserver

### ISSUE THREAD

**Issue by senthilkumar-rk** [subfission/cas#27]
Hi,

How our larave application will get logout requests from CAS Server. I mean, if cas server logged out, the cas server sending one request to client(Laravel application) according to provided service ticket. 

Kindly let us know, how can manage this logout requests in our application. If there any example, kindly share to us.

**Comment by subfission** [comment]
If the user is logged out of your CAS server, then when your web application attempts to authenticate the user it will fail and force the user to login.  If you are trying to automatically logout the user via request from your sever, then you will want a route for this server response.  Check the Wiki for an example of what the route might look like.
