### ISSUE TITLE
cas()->isAuthenticated() doesn't account for masquerade

### ISSUE THREAD

**Issue by RossIV** [subfission/cas#28]
When using the masquerade feature to bypass actual authentication, `cas()->isAuthenticated()` returns `false` instead of `true`. I've been able to work around this by modifying line 206 in `CasManager.php` to look like `return $this->config['cas_masquerade'] ? true : phpCAS::isAuthenticated();` rather than the default `return phpCAS::isAuthenticated();`. Is there a better way to work around this, or is this expected behavior?

**Comment by subfission** [comment]
Hey this was a great find!  ~~If you can supply a pull request, I will go ahead and approve it.  Your solution is exactly what I would be doing.~~ I'll fix this momentarily.

**Comment by subfission** [comment]
If you find any further issues let me know.  This should solve your needs.  

~ Thanks
