### ISSUE TITLE
Single sign out 

### ISSUE THREAD

**Issue by senthilkumar-rk** [subfission/cas#30]
Hi,

I need one help in cas SSO.

If we signout in "CAS" Server, our local(client) application does not logout.

If we logout in CAS Server, then client website also have to logout. Is there any option for this. If there please explain me, it will very help to solve our problem.

Regards,
Senthilkumar

**Comment by subfission** [comment]
Your CAS server must send a logout request to all child services.  You can capture this logout request in your app and force user logout as needed.  The method you reference on your route is: 

```
cas()->logout(); 
```

or

```
Cas::logout();
```

Example:

```
<?php

Route::get('auth/logout', function(){
  Cas::logout();
});

```
