### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by flartet** [subfission/cas#32]
Hello,
and first thanks for your CAS Middleware, it saves some time for laravel-beginners like me.

After installing it, I think it could be nice to have the installation guide, like a lot of others packages have, in the Readme. I would be glad if you could review what I wrote down and adding it to your README.

# Installation
## Composer 
`composer require subfission/cas`

## Config file
After adding the package to your project with composer, you should have a new file _config/cas.php_ containing every adjustable parameter. By default, every parameter is usable through .env conf file.
Notice there is a useful _cas_masquerade_ to force a username in a dev environment that might not have access to the CAS server.

## Adding the Service Provider and Class alias
_config/app.php_
`'providers' => [
... ,
Subfission\Cas\CasServiceProvider::class,
...
];
'aliases' => [
... ,
'Cas' => Subfission\Cas\Facades\Cas::class,
...
];`

Doing so, you're now able to call, for example in a blade template :
`{{ Cas::getCurrentUser() }} `

## Using the middleware
Having a look to https://laravel.com/docs/5.3/middleware is always a good idea.

_app\Http\Kernel.php_
You can declare the middleware in the `$middlewareGroups['web']` to apply it in every web request or only declaring it in the `$routeMiddleware = [ ... , 'cas' => \Subfission\Cas\Middleware\CASAuth::class,, ...]` to use it explicitly in the routes :
`Route::get('test', function() {})->middleware('cas');`

**Comment by subfission** [comment]
I originally had all this in the README, but moved most of it to the wiki.  Feel free to make a pull request and I'll add it.

**Comment by flartet** [comment]
So many time lost, I didn't check the Wiki part ... so many of them are empty. I feel pretty stupid :) so I am on Github I'm beginning to use.
Thanks for reply.

**Comment by subfission** [comment]
No problem!
