### ISSUE TITLE
CasManager::getAttribute() ignores cas_masquerade

### ISSUE THREAD

**Issue by borys-p** [subfission/cas#34]
There's a little inconsistency that just bit me: getAttributes() returns null with cas_masquerade enabled, but getAttribute() will forward the call to the phpCAS. Which will obviously result in fatal error.

**Comment by subfission** [comment]
Check if #35 works for what you need.  There are some additional things in this update I have been meaning to include.

**Comment by subfission** [comment]
Resolved issue with patch #35

**Comment by borys-p** [comment]
Yes, exactly what I meant, thanks!
