### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by allw1994** [subfission/cas#37]
So forgive me I am new at using laravel, I copied your example code (route::get login example) from the wiki and I can login fine, but it will not log me out and will not redirect me back? I have tried a few different examples the last being:
`Route::get('/auth/login', function(){
    cas()->authenticate();
    return redirect('home');
});`

the logout clause is here:

`Route::get('/auth/logout')->middleware('cas.auth');`

any assistance would be appreciated because this is generally clear as mud to me.

**Comment by subfission** [comment]
You missed an important part in the wiki:

```php
get('/auth/logout', [
    'middleware' => 'cas.auth', 
    function(){ 
        cas()->logout(); 
    }
]);
```

`cas()->logout(); ` does the trick!

**Comment by allw1994** [comment]
true, but tried the actual version and it still doesn't work...just displays the nice welcome to cas you've logged in page
