### ISSUE TITLE
Validating certificate

### ISSUE THREAD

**Issue by jesusvpct** [subfission/cas#39]
Hello! I'm configuring CAS enviroment variables to validate the server certificate. I've added the variable CAS_VALIDATION=ca and CAS_CERT to the path of the certificate file. But I've always see on the log the following message:

`5981 .=> phpCAS::setNoCasServerValidation() [CasManager.php:139]
5981 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
`

I don't understand why is not working.

Thanks!

**EDITED**
When calling to cas()->getConfig(), I've see something wrong:
`"cas_hostname" => "myhost"
  "cas_session_name" => "CASAuth"
  "cas_session_lifetime" => 7200
  "cas_session_path" => "/"
  "cas_control_session" => false
  "cas_port" => 443
  "cas_uri" => "/cas"
  "cas_validation" => ""
  "cas_cert" => ""
  "cas_proxy" => false
  "cas_validate_cn" => true
  "cas_login_url" => ""
  "cas_logout_url" => ""
  "cas_logout_redirect" => ""
  "cas_redirect_path" => ""
  "cas_enable_saml" => false
  "cas_debug" => "phpcas.log"
  "cas_verbose_errors" => true
  "cas_masquerade" => ""
  "cas_real_hosts" => "myhost"
  "validation" => "ca"
  "cert" => "autentica.crt"`

Instead of cas_cert and cas_validation, the config is using cert and validation.

**Comment by subfission** [comment]
Fixed in latest patch:  6adb5b1  Please update using `composer update` to receive the patch.

Thank you for finding this!

**Comment by jesusvpct** [comment]
Thanks! Working!
