### ISSUE TITLE
Cannot config:publish in Laravel 5

### ISSUE THREAD

**Issue by ridermoth** [subfission/cas#4]
I got following error when executed command "php artisan config:publish subfission/cas" =

[[InvalidArgumentException]]
Command "config:publish" is not defined.
Did you mean of these?
   vendor:publish
   config:clear
   config:cache

Please help me. Thank you very much.

**Comment by subfission** [comment]
vendor:publish is the correct answer.  I updated the readme to reflect this.  Thank you.
