### ISSUE TITLE
Improve CasManager Binding

### ISSUE THREAD

**Issue by ps** [subfission/cas#40]
As of right now in order to get the CasManager singleton, any class such as [this one](https://github.com/subfission/cas/blob/master/src/Subfission/Cas/Middleware/RedirectCASAuthenticated.php#L14) use `app('cas');`. Mocking the Laravel's `app()` helper function in unit tests is not very straightforward, if even feasible. In order to unit test properly, I ended up defining another binding in my AuthServiceProvider:
```
public function boot() {
    $this->registerPolicies();
    $this->app->bind('Subfission\Cas\CasManager', function ($app) {
           return app('cas');
    });
}
```
So that my class that requires the CasManager could type hint it in constructor as such:
```
protected $cas;

public function __construct(CasManager $casManager)
{
    $this->cas = $casManager;
}
```
Now with this setup I can easily mock CasManager and unit test properly. 

Would you be opposed to altering your CasServiceProvider to bind the singleton as follows:
```
public function register()
{
  // where 'CasManager' implements the 'CasInterface' or the interface could even be called 'Cas'
  $this->app->singleton('CasInterface', function () {
       return new CasManager( config('cas') );
  });
}
```
I can submit a pull request for it if you're ok with this change.

**Comment by ps** [comment]
I attempted to use the Facade as follows:
```
if(Cas::isAuthenticated) {
}
```
And it works fine, but when attempting to mock it as such:
```
Cas::shouldReceive('isAuthenticated')->andReturn(true);
```
I get this following error that based on Googling seems to pertain to 'phpCAS'
```
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.15-0ubuntu0.16.04.4 with Xdebug 2.4.0
Configuration: /home/pawel/my_app/phpunit.xml

<br />
<b>Error</b>: <font color="FF0000"><b>Internal script failure</b><br />
```

Another way to address this while maintaining backward compatibility with your `app('cas`);` usage would be to adjust your CasServiceProvider as such:
```
/**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $casManager = new CasManager(config('cas'));
        $this->app->singleton('cas', function () use($casManager) {
            return $casManager;
        });

        // where 'CasManager' implements the 'CasInterface' or the interface could even be called 'Cas'
         $this->app->singleton('CasInterface', function () use($casManager) {
              return $casManager;
         });
    }
```

**Comment by subfission** [comment]
Are you using Mockery or some other plugin?

**Comment by ps** [comment]
I'm using Mockery that comes by default with Laravel. If there's a way to
mock it right now without changing the package then let me know because I
didn't have much success without the additional binding that I described
earlier.

**Comment by subfission** [comment]
I think what you may be needing is the masquerading feature set in the cas.php config file.  This feature disables CAS calls for testing purposes but returns as if everything worked.

```php
    /*
    |--------------------------------------------------------------------------
    | This will cause CAS to skip authentication and assume this user id.
    | This should only be used for developmental purposes.  getAttributes()
    | will return null in this condition.
     */
    'cas_masquerade'      => env('CAS_MASQUERADE', '')
```

**Comment by ps** [comment]
That setting only helps when manually verifying functionality (and could also be handy with integration testing), but it won't help if I want to mock the return of cas functions such as:
```
$this->casMock-shouldReceive('isAuthenticated')->andReturn(false);
```
