### ISSUE TITLE
Set url logout as service

### ISSUE THREAD

**Issue by jesusvpct** [subfission/cas#45]
I'm building a multisite laravel environment with CAS. I need to use different logout_redirect for every site, but my CAS server only allow service parameter as redirect. So when passing a url on logout is not working, because parameter is called url instead of service. Can be possible to change or to add an additional parameter to logout function to use URL as service? Thanks.

**Comment by jesusvpct** [comment]
Perhaps, something as [Xavrsl](https://github.com/XavRsl/Cas/blob/master/src/Xavrsl/Cas/Sso.php) cas package:
   ```php
 /**
     * This method is used to logout from CAS
     *
     * @param array  ['url' => 'http://...'] || ['service' => ...]
     *
     * @return none
     */
    public function logout($params = array())
    {
        if($this->isPretending()) return true;
        phpCAS::logout($params);
        exit;
    }
```

**Comment by subfission** [comment]
Added to master:  e5f157e

Usage:
 
```php
$service = 'https://service.url';
$url = 'http://some.url';

cas()->logout($url, $service);
```

If you define $service, this will override your configuration/env file.

Happy coding!
