### ISSUE TITLE
New CAS version selector string passed instead of expression

### ISSUE THREAD

**Issue by defrox** [subfission/cas#48]
On the last pull request   #43 , where overriding CAS version, the version value is passed as string instead of value:
CAS_VERSION_X_0 is passed as string ('CAS_VERSION_X_0') not as a constant or value

**Comment by defrox** [comment]
Fixed on pull request #49

**Comment by subfission** [comment]
Fixed with this: 8f8ecf7.  

Check the code comments to understand if you are interested.  The solution was actually just to grab the constant() value.  I added extra comments to show the program flow and desired goal for that method.
