### ISSUE TITLE
Revision

### ISSUE THREAD

**Issue by ridermoth** [subfission/cas#5]
After I executed command "php artisan vendor:publish subfission/cas", I got some errors:

   [RuntimeException]
   Too many arguments.

But, if I execute just "php artisan vendor:publish", it succeed:

   Copied File [\vendor\subfission\cas\src\config\config.php] To [\config\cas.php] 
   Publishing Complete!

So, I think the correct command is just "php artisan vendor:publish".

Thank you very much for your cas code.

**Comment by subfission** [comment]
Yes, vendor:publish is the standard now.  It has been corrected.  Thank you for finding the typo!
