### ISSUE TITLE
Set masquerade on function?

### ISSUE THREAD

**Issue by jesusvpct** [subfission/cas#53]
Hi! I'm trying to know if there is any way to use cas_masquerade on code and not with .env file. The reason is to have a way on my web application to take the place of a user for testing purposes. This will help us to know some problems about information or actions that a user should have, see errors, etc.

On a local machine we can do this, but we have people that works only with the control panel of the application and they need this option.

Thanks in advance!

**Comment by subfission** [comment]
**Absolutely!**

The easiest way is to extend and overload CasServiceProvider.  Register _your_ service provider instead of the standard one.  In the `register()` method, you can implement a solution to inject a different value into the config:

```php
<?php namespace MyApp\Cas;
class CustomCasServiceProvider extends Subfission\Cas\CasServiceProvider
{
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('cas', function (){

            /** PLACE MODIFIER HERE **/
            $config = config('cas');
            $config['cas_masquerade'] = my_fancy_method_or_variable();

            /** LEAVE BELOW INTACT **/
            return new CasManager( $config );
        });
    }
```
