### ISSUE TITLE
CAS Authentication wanted!

### ISSUE THREAD

**Issue by cpuzzuol** [subfission/cas#56]
I recently updated to Laravel 5.5 on two separate servers. On one of the servers, when trying to log in via CAS, I get the error

CAS Authentication wanted!
You should already have been redirected to the CAS server. Click here to continue.

Clicking on the "here" link takes me to the appropriate screen, but I'm not sure what the issue could be as the code is identical on both servers. Any ideas? The phpCAS version is 1.3.5 and PHP is 7.0.27

**Comment by regnilk** [comment]
Same problem for me.

**Comment by misilot** [comment]
Same here with Laravel 5.5 with phpCAS Version 1.3.5 and PHP 7.1.13

Thanks!

**Comment by subfission** [comment]
Which tag/branch/version of this tool are you using?

**Comment by misilot** [comment]
dev-master per the directions commit 419655b87ac9f6ebe381aa0a409b6d6793359f56

**Comment by subfission** [comment]
Can you compare the issue with [tag v2.1.1](https://github.com/subfission/cas/tree/v2.1.1)?  I'm thinking it is related to the graceful termination.

**Comment by misilot** [comment]
tag v2.1.1 works as expected, redirects to CAS.

**Comment by regnilk** [comment]
It also works for me with tag v2.1.1

**Comment by subfission** [comment]
Reverted master back to tag v2.1.1 state. #57 
Thanks for the feedback~ 
And remember to lock into a tag/version for your production apps folks (use master for dev).
