### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by gudang** [subfission/cas#58]
Is it working on PHP 7.2.6? In my machine, changing session header issue.

**Comment by subfission** [comment]
Post the your debug logs and session header error you see.  Unless there were breaking changes to phpCas with 7.2, there shouldn't be any problems, although it has not been directly tested with 7.2.

**Comment by gudang** [comment]
Here's my error message. 
![error message](https://user-images.githubusercontent.com/8652780/40667489-7d39eba6-638c-11e8-8355-f5fc50c877ec.png)
Here's the phpCas.log
[phpCAS.log](https://github.com/subfission/cas/files/2048786/phpCAS.log)
When I browse the error messages in google, I got [this](https://stackoverflow.com/questions/47700336/php-7-2-warning-cannot-change-session-name-when-session-is-active)
I've tried to downgrade PHP version with 7.1.18, your extension is working.

**Comment by subfission** [comment]
Please check #59 to see if this works for you.  The documentation for 7.2 does indicate there was a breaking change to the session_name method, causing your issue.  If this patch works, I will post to master and bump the minor tag number.  ~Thank you.

**Comment by subfission** [comment]
Updates pushed to master branch.  Since the phpCas package does not officially support 7.2, I will leave this untagged until they update.
