### ISSUE TITLE
Redirect route after cas login

### ISSUE THREAD

**Issue by brunoqs** [subfission/cas#60]
I am not able to redirect a route after logging in to the cas, how can I do this? 
My route setting is:

```
Route::get('', function(){
    cas()->authenticate();
    return redirect('/carregarProfessoes');
});

Route::get('/logout', function(){
    cas()->logout();
    return redirect('/');
});
```

**Comment by subfission** [comment]
When triggering authentication, this is done by setting the redirect path in the config file: `    'cas_redirect_path'   => env('CAS_REDIRECT_PATH', ''),
`

Either set the environment variable or modify the config.
