### ISSUE TITLE
Question about CAS client and server

### ISSUE THREAD

**Issue by Ezyweb-uk** [subfission/cas#62]
Am I correct that this is a CAS client (requiring phpCAS in the build) that is designed to interface with a CAS server? If so is there a simple php CAS server that could be recommended?

**Comment by vaggelis2018** [comment]
This intended to be a cas service not a provider. A good solution is Apereo Cas

**Comment by Ezyweb-uk** [comment]
Thanks for the note about Apereo Cas, I have seen that but it looks like the server is java. I assume the subfission/cas project does not store the credentials but is instead intended to work with an ID provider. So I guess I'm looking for an open source php CAS ID provider project that subfission/cas will interface with, unless I've missunderstood (I have read the Wiki).

**Comment by subfission** [comment]
Yes, this is an interface for the Jasig CAS client.  You will need to implement a CAS server independently.
