### ISSUE TITLE
cas()->getCurrentUser()

### ISSUE THREAD

**Issue by soufianekhait** [subfission/cas#64]
Hey, I'm having an issue getting the current user through the CAS server.
I can't get the username using **cas()->getCurrentUser()**, it returns 

> Error: Internal script failure

Here's some screenshots of my **cas.php** : 

![1](https://user-images.githubusercontent.com/45060816/50825682-e9516500-1339-11e9-9a4a-d887b1e8f248.PNG)
![2](https://user-images.githubusercontent.com/45060816/50825693-f0787300-1339-11e9-8123-a067bf373780.PNG)
![3](https://user-images.githubusercontent.com/45060816/50825694-f0787300-1339-11e9-87ed-f1af9911d408.PNG)
![4](https://user-images.githubusercontent.com/45060816/50825695-f1110980-1339-11e9-982a-93b98976f97c.PNG)
![5](https://user-images.githubusercontent.com/45060816/50825702-f4a49080-1339-11e9-95fa-70a44161ded2.PNG)

Fortunately, I can connect to the server and generate a ticket but I can't get the username : 

![capture](https://user-images.githubusercontent.com/45060816/50825894-84e2d580-133a-11e9-83c0-5cc54b9f8c32.PNG)

![222](https://user-images.githubusercontent.com/45060816/50825948-a643c180-133a-11e9-8e42-778281dbfec2.PNG)

**Comment by subfission** [comment]
First thing, checked out the logs.  Also, enable verbose errors by setting `CAS_VERBOSE_ERRORS` to `true` for optimal troubleshooting.

You also need to know if your CAS provider uses SAML.  I have seen some issues with phpCAS (the core plugin this package relies on) when the wrong CAS protocol is used.

Are you using the compatible version of phpCAS?

**Comment by soufianekhait** [comment]
This is the error I get after I set `CAS_VERBOSE_ERRORS` to `true` : 
![gze](https://user-images.githubusercontent.com/45060816/51090602-676c9c00-177e-11e9-87e2-3df5b26efd54.PNG)

So weird, because I can connect to the CAS server but I can't get my username or any detail related to my account.

**Comment by soufianekhait** [comment]
I've found the solution, thank you anyway.

I set `CAS_URI` to  ` `

**Comment by subfission** [comment]
Happy to help where possible.  Best of luck!

**Comment by nguyenquan812** [comment]
> I've found the solution, thank you anyway.
> 
> I set `CAS_URI` to ` `

please tell me more detail. What did you do to fix this problem? Thank you very much
