### ISSUE TITLE
Login Controller

### ISSUE THREAD

**Issue by vitorhugomattos** [subfission/cas#65]
Is there a way I can use a controller or an app-space middleware (so I can commit it with git) to control logins? I want to make CAS auth (via `Auth::login()`) my User model, like when using Laravel's native auth system. thnx!

**Comment by vitorhugomattos** [comment]
I'll use my own middleware, sry for the noob question!

**Comment by vitorhugomattos** [comment]
Well, I'll reopen cause now I have a better question hahah how can I manage the logout? Can I do it in my middleware? I need that cause before sending the `phpCAS::logout()` request I need to force the user logout with `Auth::logout()`. This is my `handle()` method at the moment:

```
public function handle($request, Closure $next)
{
	if ($this->cas->checkAuthentication()) {
		$request->session()->put('CAS_info', $this->cas->getAttributes());

		Auth::login(User::where('CPF', $this->cas->user())->first());
	} else {
		if ($request->ajax() || $request->wantsJson()) {
			return response('Unauthorized.', 401);
		}
			
		$this->cas->authenticate();
	}

	return $next($request);
}
```

Maybe could I check for an logout request in else statement?

**Comment by thevacs** [comment]
my logout for subfission/cas 
```
    public function logout(Request $request)
    {
        $this->guard()->logout();
        $request->session()->invalidate();
        Cas()->logout();
        return $this->loggedOut($request) ?: redirect('/');
    }
```
