### ISSUE TITLE
Not updated?

### ISSUE THREAD

**Issue by Joycezhangw** [subfission/cas#68]
Do you no longer support the latest jasig/phpcas?

**Comment by zhupaizhang** [comment]
laravel 5.5   ：Error: Internal script failure

**Comment by subfission** [comment]
This is an open source project, left to support some apps that still require a SAML module for SSO auth.

I no longer do development on this package, but I'm sure the new phpcas would work just fine if you adjust the composer file to include the new version.

Feel free to test the new version and create a pull request if there are no issues.
