### ISSUE TITLE
Multiple laravel apps with single sign on? How?

### ISSUE THREAD

**Issue by rasyidly** [subfission/cas#69]
I have 2 (or more) laravel apps, different domain, and non HTTPS (just call ``authdomain.test`` and ``appdomain1.test``).. anyone know how to sign in ``appdomain1.test`` from ``authdomain.test``? Where should I place this package? for client? or server? How to make it all like google account (``authdomain``) with all services, like mail, drive, etc. (``appdomain1.test``)
Can anyone give me the simple example? thanks.. Im confused here for a week.. thanks..

**Comment by subfission** [comment]
This can all be done through session cookies.  I would recommend caching your user's active session in Redis and unlike Google, implementing some expiration function that is reset every time the user navigates back to the domain.

You will need custom **middleware** and **auth guard** for this, but is pretty easy to build.

Reopen this if you have any more questions on this topic.
