### ISSUE TITLE
PHP Laravel Unit Test

### ISSUE THREAD

**Issue by Swaroo** [subfission/cas#73]
Is there a way to Unit test our controllers which are wrapped with CAS middleware?
I try the normal way and got Internal Script failure. But that is understandable as the user is not logged in.
I tried masquerading with a custom user, but still got Internal Script failure while testing. 

![image](https://user-images.githubusercontent.com/13852426/69091651-989da480-09ff-11ea-9974-f3b38b2c0544.png)

Here's the shot of the route:
![image](https://user-images.githubusercontent.com/13852426/69091820-f205d380-09ff-11ea-9fe4-3f76874445d9.png)

Here's the basic test case:
![image](https://user-images.githubusercontent.com/13852426/69093782-0c41b080-0a04-11ea-87f3-246d8bb0431e.png)

**Comment by Swaroo** [comment]
Although if I masquerade with some user and run unit tests with --stderr flag, it seems to masquerade properly and run unit tests successfully.

**Comment by subfission** [comment]
Great question.  In my unit tests I had to add logic to bypass cas auth or it would trigger the CAS request.  It has been a while, but I did this inside the middleware itself.  (I'm sure there are a few different ways)

**Comment by rgetty** [comment]
Disclaimer: I'm pretty new to Laravel (and phpunit) and I was not the original developer on the project.

I would have figured including `use WithoutMiddleware;` in my test class would have bypassed CAS.

After setting CAS_VERBOSE_ERRORS to true, when I run phpunit to run a simple 
`$this->get('/')->assertStatus(200);`, I get:

`phpCAS error: phpCAS::client(): ErrorException: session_start(): Cannot start session when headers already sent in /Users/rgetty/Projects/php/falconlink/vendor/subfission/cas/src/Subfission/Cas/CasManager.php on line 97`

**Comment by subfission** [comment]
@rgetty 
The middleware handles the CAS calls, but the service provider sets up the CAS manager.  During the execution flow, if you are masquerading it will try to inject a cookie to manually authenticate you.  The error is telling you that laravel already sent the headers for the packet, so there is no way to send the cookie (race condition).  You will need to check your code for something already passing the request to the browser... I feel your pain adopting other people's code.

@Swaroo 
On line 49 of CASManager.php manually add:

`if ( $this->config['cas_masquerade'] ) { $this->_masquerading = true; return true; }`

Let me know if that helps fix your issue.

**Comment by subfission** [comment]
No further updates- closing.

**Comment by Swaroo** [comment]
> @rgetty
> The middleware handles the CAS calls, but the service provider sets up the CAS manager. During the execution flow, if you are masquerading it will try to inject a cookie to manually authenticate you. The error is telling you that laravel already sent the headers for the packet, so there is no way to send the cookie (race condition). You will need to check your code for something already passing the request to the browser... I feel your pain adopting other people's code.
> 
> @Swaroo
> On line 49 of CASManager.php manually add:
> 
> `if ( $this->config['cas_masquerade'] ) { $this->_masquerading = true; return true; }`
> 
> Let me know if that helps fix your issue.

Thank you for your answer. I'll check it out and let you know.

**Comment by albertski** [comment]
@subfission Do you by any chance know if there is a way to prevent the CAS from running in PHPUnit test without modifying the code?  I was thinking that I would be able to bind the class but I'm still getting the `ErrorException: session_start(): Cannot start session when headers already sent in /var/www/html/vendor/subfission/cas/src/Subfission/Cas/CasManager.php</b> on line 97` error.  I tried the below but it still calls the default CasManager:

```
    protected function setUp(): void
    {
        parent::setUp();

        $this->app->instance(CasManager::class, TestCasManager::class);
    }
```

```
    protected function setUp(): void
    {
        parent::setUp();

        $this->app->bind(CasServiceProvider::class, function() {
            return new CasServiceProviderFaker();
        });
    }
```

**Comment by albertski** [comment]
Actually I was able to figure it out:

```
protected function setUp(): void
    {
        parent::setUp();

        $this->app->singleton('cas', function () {
            return new TestCasManager();
        });

        Cas::shouldReceive('isAuthenticated')
            ->andReturn(NULL);
        Cas::shouldReceive('user')
            ->andReturn(NULL);
        Cas::shouldReceive('logout')
            ->andReturn(NULL);
        Cas::shouldReceive('client')
            ->andReturn(NULL);
    }
```

```
<?php

namespace Tests;

class TestCasManager {

}
```

**Comment by subfission** [comment]
Nailed it.
