### ISSUE TITLE
session file is writing to hd root

### ISSUE THREAD

**Issue by fbmfbm** [subfission/cas#74]
Hi all,
I'm upgrading Laravel app from 5.4 to 5.8 and php7.2  and i'm facing strange trouble with auth session : 
I'm getting this error " file_put_contents(/idrqlxdraQp8Ek97LIAiF4vFNGN5KX8CI4aE9Y4F): failed to open stream: Permission denied " on login but session file path is correctly setup in configuration file (framework/session). 
I'm clearing all cache and config but the problem is allway present !! 
I'm think that Cas frameworke is the source of trouble and searching but nothing to do ...
Any one have some idea ??

Thank's 
fbm

**Comment by subfission** [comment]
Sounds like this file path may not be set with correct permissions...  It is likely that PHP does not have permissions set to edit the file.

try `ls -lah` on that directory and files and look for write permissions associated to the user.
