### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by ferox** [subfission/cas#77]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.7.28
    - Conclusion: don't install laravel/framework v5.7.28
    - Conclusion: don't install laravel/framework v5.7.27
    - Conclusion: don't install laravel/framework v5.7.26
    - Conclusion: don't install laravel/framework v5.7.25
    - Conclusion: don't install laravel/framework v5.7.24
    - Conclusion: don't install laravel/framework v5.7.23
    - Conclusion: don't install laravel/framework v5.7.22
    - Conclusion: don't install laravel/framework v5.7.21
    - Conclusion: don't install laravel/framework v5.7.20
    - Conclusion: don't install laravel/framework v5.7.19
    - Conclusion: don't install laravel/framework v5.7.18
    - Conclusion: don't install laravel/framework v5.7.17
    - Conclusion: don't install laravel/framework v5.7.16
    - Conclusion: don't install laravel/framework v5.7.15
    - Conclusion: don't install laravel/framework v5.7.14
    - Conclusion: don't install laravel/framework v5.7.13
    - Conclusion: don't install laravel/framework v5.7.12
    - Conclusion: don't install laravel/framework v5.7.11
    - Conclusion: don't install laravel/framework v5.7.10
    - Conclusion: don't install laravel/framework v5.7.9
    - Conclusion: don't install laravel/framework v5.7.8
    - Conclusion: don't install laravel/framework v5.7.7
    - Conclusion: don't install laravel/framework v5.7.6
    - Conclusion: don't install laravel/framework v5.7.5
    - Conclusion: don't install laravel/framework v5.7.4
    - Conclusion: don't install laravel/framework v5.7.3
    - Conclusion: don't install laravel/framework v5.7.2
    - Installation request for subfission/cas dev-master -> satisfiable by subfission/cas[dev-master].
    - Conclusion: don't install laravel/framework v5.7.1
    - Conclusion: don't install laravel/framework v5.7.0
    - subfission/cas dev-master requires illuminate/support 6.x -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0].
    - Can only install one of: laravel/framework[6.x-dev, 5.7.x-dev].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.0.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.0.1|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.0.2|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.0.3|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.0.4|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.1.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.2.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.3.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.4.1|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.5.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.5.1|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.5.2|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.6.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.6.1|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.6.2|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/support v6.7.0|don't install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework 5.7.* -> satisfiable by laravel/framework[5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.12, v5.7.13, v5.7.14, v5.7.15, v5.7.16, v5.7.17, v5.7.18, v5.7.19, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.24, v5.7.25, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].

**Comment by subfission** [comment]
Looks like you didn't lock your updates to a version number.  Version 3.x.x of this plugin is for Laravel 6.x. It appears you are using Laravel 5.x.  So you should keep your composer file restricted to subfission/cas:2.x.x

Dev-master branch is for testing bleeding edge.

**Comment by subfission** [comment]
Try this:

`$ composer require "subfission/cas":"<3.*"
`

**Comment by ferox** [comment]
I had to change aliases entry 'Cas' => Subfission\Cas\Facades\Cas::class,

Also a I had to add into providers the entry Subfission\Cas\CasServiceProvider::class,

Which file? config/app.php

**Comment by ferox** [comment]
I had to change the providers and alias

> Looks like you didn't lock your updates to a version number. Version 3.x.x of this plugin is for Laravel 6.x. It appears you are using Laravel 5.x. So you should keep your composer file restricted to subfission/cas:2.x.x
> 
> Dev-master branch is for testing bleeding edge.

OK.

**Comment by subfission** [comment]
Oh, you would make this change in your composer files in the root of your project.  composer.json and composer.lock

**Comment by subfission** [comment]
It does not sound like anything further is needed.  I'll go ahead and close this.

**Comment by ferox** [comment]
OK.

**Comment by yohannanv** [comment]
Hi,

I am unable to install subfission package in my Laravel 5.7 application. So I created new laravel 7 application and installed subfission through composer. Then I copied the vendor/subfission folder from my laravel 7 to laravel 5.7 vendor folder. After I modified the app.php of my laravel 5.7 application as mentioned in subfission wiki installation. When I run the 5.7 application its throwing 500 error. In my log file I can see this error - local.ERROR: Uncaught ReflectionException: Class view does not exist in vendor/laravel/framework/src/Illuminate/Container/Container.php:774

How can I rectify this error?

Please help me.
