### ISSUE TITLE
Artisan route:list fails

### ISSUE THREAD

**Issue by happymacarts** [subfission/cas#82]
from my composer file 
...
 "require": {
        "php": "^7.1.3",
        "adldap2/adldap2-laravel": "^6.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "subfission/cas": "~2.1",
        "doctrine/dbal": "^2.10"
    },
...

[$> artisan route:list ](url)
results in errors

  ErrorException  : Undefined index: HTTP_HOST

  at /usr/local/www/sites/intra/vendor/jasig/phpcas/source/CAS/Client.php:3625
    3621|         } else if (!empty($_SERVER['HTTP_X_FORWARDED_SERVER'])) {
    3622|             $server_url = $_SERVER['HTTP_X_FORWARDED_SERVER'];
    3623|         } else {
    3624|             if (empty($_SERVER['SERVER_NAME'])) {
  > 3625|                 $server_url = $_SERVER['HTTP_HOST'];
    3626|             } else {
    3627|                 $server_url = $_SERVER['SERVER_NAME'];
    3628|             }
    3629|         }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: HTTP_HOST", "/usr/local/www/sites/intra/vendor/jasig/phpcas/source/CAS/Client.php", [])
      /usr/local/www/sites/intra/vendor/jasig/phpcas/source/CAS/Client.php:3625

  2   CAS_Client::_getClientUrl()
      /usr/local/www/sites/intra/vendor/jasig/phpcas/source/CAS/Client.php:3571

  Please use the argument -v to see more details.

   Whoops\Exception\ErrorException  : Module 'imagick' already loaded

  at Unknown:0
    1|

  Exception trace:

  1   Whoops\Run::handleError("Module 'imagick' already loaded", "Unknown")
      /usr/local/www/sites/intra/vendor/filp/whoops/src/Whoops/Run.php:408

  2   Whoops\Run::handleShutdown()
      [internal]:0

**Comment by subfission** [comment]
What does your config and middleware look like?  

This error indicates your code is attempting to make a request to your SSO provider but you are using CLI.

I'm thinking this issue has something to do with the app making a CAS call outside of the middleware.

**Comment by subfission** [comment]
Please obfuscate any sensitive data before submitting your config.

**Comment by subfission** [comment]
Closing topic.
