### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by coolsam726** [subfission/cas#84]
Plans to support Laravel 8? Should I do a pull request?

**Comment by subfission** [comment]
Feel free!  The modifications should be relatively small.

**Comment by desyashasyi** [comment]
yes.. how to use it in Laravel 8?

**Comment by coolsam726** [comment]
> yes.. how to use it in Laravel 8?

@desyashasyi I have already done a PR to support Laravel 8, @subfission we are waiting for you to merge and tag a new version for this. Thanks.

**Comment by desyashasyi** [comment]
> @desyashasyi I have already done a PR to support Laravel 8, @subfission we are waiting for you to merge and tag a new version for this. Thanks.
@subfission , we are waiting :-).

**Comment by desyashasyi** [comment]
Thank you very much
