### ISSUE TITLE
Use case for cas.guest Middleware?

### ISSUE THREAD

**Issue by orware** [subfission/cas#92]
I have been using this package for a bit now and did some fine-tuning of how I'll be using it at the end of last week, but I wanted to ask if the use case for the `cas.guest` middleware could be clarified a bit in the Wiki?

At the moment I'm not 100% sure how to best make use of it (or which situations it'll make sense to use it in), so at the moment I think I'll only be utilizing the other `cas.auth` middleware only, but would like to know more just in case the other one might be useful in some way.

Also, as mentioned in #90, I'm not sure what the best approach is to having an associated user record created for logged in users right now (perhaps the code could just be integrated into the AppServiceProvider.php file for my Laravel app), but from what I've been reading it seems like I should be able to run the cas()->isAuthenticated() check somewhere and then maybe trigger a user record to be created/updated at that point, which also means I probably should make some adjustments to the fields my user table will include to help match the attributes I'm sending back from CAS, and to mark the password field as nullable, which is a tip I saw in a Laracasts forum thread somewhere when running some Google searches a few days (although it seems like we'd only want that to be triggered once per session, rather than on every page load).

It would be nice to have maybe some of these extra scenarios for a real-world application maybe described in a little more detail, since like @drupol in Issue #90, I'm wrapping my head around the full breadth of the various Laravel authentication offerings, but none of them seem to really target the higher education market very well so the other options like Passport, Socialite, etc. are a bit more integrated into the Laravel way of doing things it seems, but at the same time I can't easily integrate with them for our SSO needs (I spent the last two days trying to see if I could create a Laravel Socialite Provider on my own to possibly integrate with the OpenID Connect option our PortalGuard SSO software offers, in addition to the CAS and SAML protocols...but I wasn't able to get the OpenID Connect option working so I'm back to using CAS since I at least know I can authenticate successfully with this SSO option at the moment :-).

I'm happy to help where I can (I just don't feel like I have all the correct Laravel-specific answers at the moment).

**Comment by subfission** [comment]
I would typically add the auth check to your auth guard in Laravel (but there are many ways to go about this).  You would then add the middleware to your controllers for the pages that need CAS.  For guest-accessible pages, you would just omit the middleware.

I'm debating creating a laravel with CAS app, but limited on time to do such things.  Feel free to submit a pull request.

Happy coding :)
